name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prep
      shell: bash
      run: sudo apt install libcmocka-dev libarchive-dev
    - name: Build
      shell: bash
      run: make -C native
    - name: Test
      shell: bash
      run: make -C native test
